default_platform(:ios)

platform :ios do
  desc "Deploy to App Store"
  lane :deploy do
    build_app(scheme: "{{SCHEME_NAME}}")
    upload_to_app_store
  end
end

platform :android do
  desc "Deploy to Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store
  end
end

