"""add_missing_tables

Revision ID: 4f5fabfd4d44
Revises: 1f06f512a137
Create Date: 2025-07-04 17:58:15.679891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5fabfd4d44'
down_revision: Union[str, None] = '1f06f512a137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_service_professional', 'service_professionals_association', ['service_id', 'professional_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_professional', 'service_professionals_association', type_='unique')
    # ### end Alembic commands ###
