"""add nickname to users

Revision ID: 5422fcd5575d
Revises: 9bd2067abc1d
Create Date: 2025-07-01 11:44:26.430754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5422fcd5575d'
down_revision: Union[str, None] = '9bd2067abc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_groups', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'WALK_IN', 'PARTIALLY_COMPLETED', 'READY_TO_PAY', 'IN_SERVICE', 'CONFIRMED', 'ARRIVED', name='appointment_groups_status_enum'),
               type_=sa.Enum('SCHEDULED', 'CONFIRMED', 'WALK_IN', 'ARRIVED', 'IN_SERVICE', 'READY_TO_PAY', 'COMPLETED', 'CANCELLED', 'PARTIALLY_COMPLETED', name='appointmentgroupstatus'),
               existing_nullable=False)
    op.drop_index('appointment_groups_client_id_idx', table_name='appointment_groups')
    op.drop_index('appointment_groups_start_time_idx', table_name='appointment_groups')
    op.drop_index('appointment_groups_status_idx', table_name='appointment_groups')
    op.create_index(op.f('ix_appointment_groups_client_id'), 'appointment_groups', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointment_groups_start_time'), 'appointment_groups', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointment_groups_status'), 'appointment_groups', ['status'], unique=False)
    op.create_foreign_key(None, 'appointment_groups', 'users', ['client_id'], ['id'])
    op.alter_column('appointments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'WALK_IN', 'READY_TO_PAY', 'IN_SERVICE', 'ARRIVED', name='appointments_status_enum'),
               server_default=None,
               type_=sa.Enum('SCHEDULED', 'CONFIRMED', 'WALK_IN', 'ARRIVED', 'IN_SERVICE', 'READY_TO_PAY', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'),
               existing_nullable=True)
    op.alter_column('appointments', 'paid_manually',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('appointments_professional_id_idx', table_name='appointments')
    op.drop_index('appointments_service_id_idx', table_name='appointments')
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_group_id'), 'appointments', ['group_id'], unique=False)
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_foreign_key(None, 'appointments', 'appointment_groups', ['group_id'], ['id'])
    op.alter_column('professional_availability', 'day_of_week',
               existing_type=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='professional_availability_day_enum'),
               type_=sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'),
               existing_nullable=False)
    op.drop_index('professional_availability_professional_user_id_day_of_week_idx', table_name='professional_availability')
    op.create_index(op.f('ix_professional_availability_professional_user_id'), 'professional_availability', ['professional_user_id'], unique=False)
    op.create_unique_constraint('uq_prof_avail_day_time_slot', 'professional_availability', ['professional_user_id', 'day_of_week', 'start_time', 'end_time'])
    op.create_foreign_key(None, 'professional_availability', 'users', ['professional_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('professional_blocked_time', 'block_type',
               existing_type=postgresql.ENUM('break', 'vacation', 'sick_leave', 'other', name='professional_blocked_time_block_type_enum'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index('professional_blocked_time_professional_user_id_blocked_date_idx', table_name='professional_blocked_time')
    op.create_index(op.f('ix_professional_blocked_time_professional_user_id'), 'professional_blocked_time', ['professional_user_id'], unique=False)
    op.create_unique_constraint('uq_prof_blocked_date_slot_type', 'professional_blocked_time', ['professional_user_id', 'blocked_date', 'start_time', 'end_time', 'block_type'])
    op.create_foreign_key(None, 'professional_blocked_time', 'users', ['professional_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('professional_breaks', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('professional_breaks', 'day_of_week',
               existing_type=postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='professional_availability_day_enum'),
               type_=sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'),
               existing_nullable=False)
    op.create_index(op.f('ix_professional_breaks_professional_user_id'), 'professional_breaks', ['professional_user_id'], unique=False)
    op.create_index(op.f('ix_professional_breaks_tenant_id'), 'professional_breaks', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_prof_break_day_time_slot', 'professional_breaks', ['professional_user_id', 'day_of_week', 'start_time', 'end_time'])
    op.create_foreign_key(None, 'professional_breaks', 'users', ['professional_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('service_categories', 'display_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint(None, 'service_categories', ['name'])
    op.drop_index('service_professionals_association_professional_user_id_idx', table_name='service_professionals_association')
    op.create_unique_constraint('uq_service_professional', 'service_professionals_association', ['service_id', 'professional_user_id'])
    op.create_foreign_key(None, 'service_professionals_association', 'users', ['professional_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_professionals_association', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'parallelable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'max_parallel_pros',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('services_category_id_idx', table_name='services')
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_foreign_key(None, 'services', 'service_categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CLIENTE', 'PROFISSIONAL', 'ATENDENTE', 'GESTOR', name='users_role_enum'),
               type_=sa.Enum('CLIENTE', 'PROFISSIONAL', 'ATENDENTE', 'GESTOR', name='userrole'),
               existing_nullable=False)
    op.alter_column('users', 'hair_type',
               existing_type=postgresql.ENUM('LISO', 'ONDULADO', 'CACHEADO', 'CRESPO', name='users_hair_type_enum'),
               type_=sa.Enum('LISO', 'ONDULADO', 'CACHEADO', 'CRESPO', name='hairtype'),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MASCULINO', 'FEMININO', 'OUTROS', name='users_gender_enum'),
               type_=sa.Enum('MASCULINO', 'FEMININO', 'OUTROS', name='gender'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_users_address_cep', table_name='users')
    op.drop_index('ix_users_address_city', table_name='users')
    op.drop_index('ix_users_address_state', table_name='users')
    op.drop_index('users_email_idx', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('users', 'nickname')

