"""Add social login fields to users table

Revision ID: add_social_login_fields
Revises: f723970576f6
Create Date: 2025-06-28 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_social_login_fields'
down_revision = 'f723970576f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add social login fields to users table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('social_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    
    # Add unique constraint for social_provider + social_id combination
    op.create_index('idx_users_social_provider_id', 'users', ['social_provider', 'social_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove social login fields from users table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_social_provider_id', table_name='users')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'social_provider')
    # ### end Alembic commands ###