// This file is auto-generated by the build script
// Default tokens will be replaced with brand-specific tokens during build

const tokens = {
  colors: {
    primary: "#6366f1",
    primaryDark: "#4f46e5",
    secondary: "#e879f9",
    background: "#ffffff",
    surface: "#f8fafc",
    text: "#1e293b",
    textSecondary: "#64748b",
    border: "#e2e8f0",
    success: "#10b981",
    warning: "#f59e0b",
    error: "#ef4444"
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px"
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px"
  },
  typography: {
    fontFamily: {
      regular: "System",
      medium: "System",
      bold: "System"
    },
    fontSize: {
      xs: "12px",
      sm: "14px",
      md: "16px",
      lg: "18px",
      xl: "20px",
      "2xl": "24px"
    }
  }
};

module.exports = tokens;