name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: [ 'torri-apps/Web-admin/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'torri-apps/Web-admin/**' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: torri-apps/Web-admin/package-lock.json
    
    - name: Install dependencies
      run: |
        cd torri-apps/Web-admin
        npm ci
    
    - name: Run tests
      run: |
        cd torri-apps/Web-admin
        echo "Skipping tests for now - will set up test suite later"
        # npm test -- --coverage --watchAll=false
    
    - name: Build application
      run: |
        cd torri-apps/Web-admin
        npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-files
        path: torri-apps/Web-admin/build/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io
    
    - name: Build Docker image
      run: |
        cd torri-apps/Web-admin
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:${{ github.sha }} .
        docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:latest
    
    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:${{ github.sha }}
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy torri-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/torri-frontend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5