name: Mobile CI

on:
  push:
    branches: [ main, develop ]
    paths: [ 'torri-apps/Mobile-client-core/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'torri-apps/Mobile-client-core/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: torri-apps/Mobile-client-core/package-lock.json
    
    - name: Install dependencies
      run: |
        cd torri-apps/Mobile-client-core
        npm ci
    
    - name: Run tests
      run: |
        cd torri-apps/Mobile-client-core
        npm test -- --coverage --watchAll=false
    
    - name: Run linting
      run: |
        cd torri-apps/Mobile-client-core
        npm run lint