name: White-label Deploy

on:
  workflow_dispatch:
    inputs:
      brand:
        description: 'Brand to deploy'
        required: true
        type: choice
        options:
        - luxe-salon
        - beauty-hub
        - glamour-studio
        - urban-salon
      platform:
        description: 'Platform to deploy'
        required: true
        type: choice
        options:
        - ios
        - android
        - both

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install Fastlane
      run: gem install fastlane
    
    - name: Deploy white-label app
      run: |
        chmod +x torri-apps/Infrastructure/Scripts/White-label-deploy.sh
        ./torri-apps/Infrastructure/Scripts/White-label-deploy.sh ${{ github.event.inputs.brand }} ${{ github.event.inputs.platform }}
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}